### PR TITLE
Fix: Glug should ignore directory symlinks by default

### LINKED ISSUE #33: Glug should ignore directory symlinks by default
#31 shows failures in repos using directory symlinks. As they pose significant questions listed below, the current behavior should be changed to ignore them. File symlinks should be more or less safe, as at most they probably result in duplicate results.

* duplicate results - Similar as for file symlinks, but on a much larger scope.
* cycle detection - Symlinks can create cyclic trees, causing infinite loops that should be detected and prevented.
* filtering - Should filtering be done on real path or linked one? E.g. for `foo/bar -> baz` what happens if user asks to only search one directory or wants to explicitly ignore it?

### PR DESCRIPTION
**Pull request by dkaszews**
Resolves #33

### CODE REVIEW

File: test/unit/test_glob_filter.cpp [hunk 1]
```diff
@@ -52,82 +51,82 @@ static const auto filter_cases = std::vector<filter_param>{
...
-            { "dir/dir_only", decision::undecided },
-            { "dir/dir_only/", decision::ignored },
-            // Files in ignored directories are not ignored explicitly,
-            // but are ignored implicitly as they will not be enumerated.
-            { "dir_only/file", decision::undecided },
+            { "dir_only"_f, decision::undecided },
+            { "dir_only"_d, decision::ignored },
+            { "dir"_d / "dir_only"_f, decision::undecided },
+            { "dir"_d / "dir_only"_d, decision::ignored },
+            // // Files in ignored directories are not ignored explicitly,
```
Comment (dkaszews) [inline test/unit/test_glob_filter.cpp]: Doubled comment
