### PR TITLE
Fix: Search does not consider outer .gitignore files

### LINKED ISSUE #17: Search does not consider outer .gitignore files
When using `glug` to search a directory, it only considers `.gitignore` files inside that directory and its subdirectories. This is inconsistent with `git ls-files`, which always ignores the same files, regardless of where you started.

Repro:

```bash
$ find -type f
.gitignore
this_should_be_visible
this_should_not_be_visible
dir/this_should_be_visible
dir/this_should_not_be_visible

$ cat .gitignore
*not*

$ glug
.gitignore
this_should_be_visible
dir/this_should_be_visible

$ glug dir
dir/this_should_be_visible
dir/this_should_not_be_visible
```

Proposed fix is to use `.git` directories as markers for start of the repository, if the requested directory does not contain a `.git` directory, then recursively look in parents. If one is find higher up, then load all `.gitignore` files from there to here.

Similar consideration should be for nested repositories (submodules), as the `.gitignore` in parent should not affect files in child:

```bash
$ find -type f
.gitignore
submodules/repo/.git/HEAD
submodules/repo/test.log
submodules/repo/README.md

$ cat .gitignore
*.log

$ glug
.gitignore
submodules/repo/README.md
```

The simplest way to solve it would likely be to ignore submodules, i.e. do not enumerate any directories which contain `.git` directory other than the explicitly requested one.

### PR DESCRIPTION
**Pull request by dkaszews**
Also adds parity self-tests, using `glug` repo itself as test data, since after building and cloning other repos, it is filled with ignored files.

Resolves #17

### CODE REVIEW

File: src/filesystem.cpp [hunk 1]
```diff
@@ -52,12 +57,45 @@ static glob::filter make_filter(const std::filesystem::path& path) {
...
+static std::vector<fs::path> gather_gitignores(const fs::path& path) {
+    if (fs::is_directory(path / ".git")) {
+        return {};
+    }
+
+    auto current = path;
+    auto result = std::vector<fs::path>{};
+
+    // False branch unreachable in UT by design, see `temp_fs::temp_fs`
+    while (current.has_parent_path()) {  // GCOVR_EXCL_LINE
```
Comment (dkaszews) [inline src/filesystem.cpp]: Better idea:

```cpp
static bool is_root(const fs::path& path) {
#ifdef UNIT_TEST
    // In UT, "root" dir is `/tmp/glug_test.*/`
    if (path.parent_path() == fs::temp_dir()) {
        return true;
    }
#endif
    return !path.has_parent_path();

File: test/unit/tree.cpp [hunk 2]
```diff
@@ -17,7 +17,10 @@ static std::filesystem::path make_temp_directory() {
 }
 
 temp_fs::temp_fs() :
-    path_{ make_temp_directory() } {}
+    path_{ make_temp_directory() } {
```
Comment (dkaszews) [inline test/unit/tree.cpp]: Revert
